import React from "react"
import { Box, Button, Typography, useMediaQuery, useTheme } from "@mui/material"
import Link from "next/link"

function ExploreTopics() {
	const theme = useTheme()
	const isSmallScreen = useMediaQuery(theme.breakpoints.down("sm"))

	return (
		<Link href="/speak" style={{ width: "fit-content" }}>
			<Box
				sx={{
					boxShadow: "rgba(50, 50, 93, 0.05) 0px 2px 5px -1px, rgba(0, 0, 0, 0.2) 0px 1px 3px -1px",
					maxHeight: { xs: "90vh", sm: "280px" },
					height: { xs: "55vh", sm: "280px" },
					width: "100%",
					borderRadius: "8px",
					cursor: "pointer",
					transition: "transform 0.3s ease-in-out",
					overflow: "hidden",
					position: "relative",
					background: "linear-gradient(45deg, #8b58fe, #5fdee7)",
					"&:hover": {
						cursor: "pointer",
						transform: "scale(1.01)",
					},
					display: "flex",
				}}
			>
				{isSmallScreen ? (
					<img
						src={"/online-courses.svg"}
						alt="book"
						style={{ position: "absolute", width: "120%", height: "100%", top: -70, left: -35 }}
					/>
				) : (
					<img
						src={"/online-courses.svg"}
						alt="book"
						style={{ position: "absolute", width: "120%", height: "120%", marginTop: -50, marginLeft: 135 }}
					/>
				)}
				<Box
					sx={{
						display: "flex",
						flexDirection: "column",
						margin: " 0px auto",
						padding: "0px 30px 10px",
						height: "100%",
						width: "100%",
						alignItems: { xs: "center", sm: "flex-start" },
						justifyContent: { xs: "flex-end", sm: "center" },
					}}
				>
					<Typography
						fontWeight="bolder"
						sx={{
							color: "#001663",
							zIndex: 99,
							mb: 1,
							fontSize: { xs: 28, sm: 46 },
							textAlign: { xs: "center", sm: "flex-start" },
						}}
					>
						Explore Topics
						<Typography sx={{ textAlign: { xs: "center", sm: "start" } }}>Generated by AI</Typography>
					</Typography>
					<Button variant="outlined" sx={{ color: "white", border: "1px solid white", width: "fit-content" }}>
						View
					</Button>
				</Box>
			</Box>
		</Link>
	)
}

export default ExploreTopics
