export const lessonDescription = {
	general_english:
		"General English classes provide a comprehensive foundation in the English language. Students develop skills in reading, writing, speaking, and listening, enhancing their ability to communicate effectively in everyday situations. These classes cater to learners of all levels, from beginners to advanced, fostering fluency and confidence.",
	speaking_club:
		"At the Speaking Club, students engage in English practice through a wide array of topics generated by AI and interact with fellow learners. This dynamic setting encourages participants to refine their speaking skills by discussing diverse subjects, thus enhancing fluency, vocabulary, and overall conversational prowess in a collaborative learning environment.",
	business_english:
		"Business English classes cater to professionals aiming to excel in the corporate world. Students learn to communicate effectively in a business context, mastering skills such as email correspondence, presentation delivery, negotiation, and professional writing, enabling success in international business environments.",
	ielts:
		"IELTS preparation courses are tailored to help students achieve their target scores in the IELTS exam. These classes encompass all test sections, focusing on listening, reading, writing, and speaking skills. Students receive intensive training to meet their academic and immigration aspirations.",
	toefl:
		"TOEFL classes prepare students for the TOEFL exam, a requirement for university and college admissions in English-speaking countries. The curriculum emphasizes academic English proficiency, encompassing reading comprehension, listening comprehension, essay composition, and spoken English skills.",
}
